# vim: set ft=ansible:
---
- name: Install OpenShift installer packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - "atomic-openshift-utils"
      - "atomic-openshift-{{ osrelease }}"
      - "httpd-tools"
  tags:
   - install_openshift_provisioner_packages
